**Question 1**

In [ ]:
import numpy as np
ar = np.arange(2,51,3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


**Question 2**

In [ ]:
 
 
import numpy as np
a1=[] 
a2=[]
for i in range(0, 5): 
    ele = int(input())
    a1.append(ele)
for i in range(0, 5): 
    ele = int(input())
    a2.append(ele) 
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))

1
3
4
3
5
6
7
8
9
3
[1 3 4 3 5 6 7 8 9 3]
[1 3 3 3 4 5 6 7 8 9]


**Question 3**

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[1,3,5],[1,3,4]])
print(arr.ndim)
print(arr.size)

2
9


 **Question 4**

In [ ]:
import numpy as np
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)

1
2


**Question 5**

In [ ]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print() 
print(np.hstack((arr1,arr2)))

[[0.75324593 0.76767646 0.95745839]
 [0.7182216  0.1936309  0.88660924]
 [0.91286027 0.99548127 0.10861992]
 [0.30206087 0.34987646 0.438962  ]
 [0.22004795 0.51214668 0.56346949]
 [0.31108077 0.19336093 0.47606074]]

[[0.75324593 0.76767646 0.95745839 0.30206087 0.34987646 0.438962  ]
 [0.7182216  0.1936309  0.88660924 0.22004795 0.51214668 0.56346949]
 [0.91286027 0.99548127 0.10861992 0.31108077 0.19336093 0.47606074]]


**Question 6**

In [ ]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3]))
